module ActiveRecord #:nodoc:
  module Acts #:nodoc:
    module Taggable #:nodoc:
      module SingletonMethods
                
        # paginate records having same tag(s)
        def paged_find_tagged_with(tags, args = {})
          if tags.blank?
            paginate args
          else
            options = find_options_for_find_tagged_with(tags, :match_all => true)
            options.merge!(args)
            # The default count query generated by paginate includes COUNT(DISTINCT Posts.*) which errors, at least on mysql
            # Below we override the default select statement used to perform the count so that it becomes COUNT(DISTINCT Posts.id)
            paginate(options.merge(:count => { :select => options[:select].gsub('*', 'id') }))
          end
        end
        
      end
    end
  end
end